from django.conf.urls.defaults import *

urlpatterns = patterns('',
  url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[-\w]+)/$',
	view	= 'patrickbeeson.apps.blog.views.entry_detail',
	name	= 'blog_detail',
  ),  
  url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', 
	view	= 'patrickbeeson.apps.blog.views.entry_archive_day',
	name	= 'blog_archive_day',
  ),
  url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
	view	= 'patrickbeeson.apps.blog.views.entry_archive_month',
	name	= 'blog_archive_month',
  ),
  url(r'^(?P<year>\d{4})/$',
	view	= 'patrickbeeson.apps.blog.views.entry_archive_year',
	name	= 'blog_archive_year',
  ),
  url(r'^tags/(?P<slug>[-\w]+)/$',
	view	 = 'patrickbeeson.apps.blog.views.tag_detail',
	name	 = 'blog_tag_detail',
  ),
  url (r'^tags/$',
	view	= 'patrickbeeson.apps.blog.views.tag_list',
	name	= 'blog_tag_list',
  ),
  url (r'^search/$',
	view	= 'patrickbeeson.apps.blog.views.search',
	name	= 'blog_search',
  ),
  url(r'^page/(?P<page>\w)/$',
	view	= 'patrickbeeson.apps.blog.views.entry_list',
	name	= 'blog_index_paginated',
  ),
  url(r'^archive/$',
	view	= 'patrickbeeson.apps.blog.views.entry_list',
	name	= 'blog_index',
  ),
)